# Generated by Django 2.2.9 on 2020-01-25 22:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('degat', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)])),
                ('poids', models.PositiveIntegerField(default=1)),
                ('prix', models.PositiveIntegerField(default=1)),
                ('Propriétés', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Personnage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=200)),
                ('force', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(21)])),
                ('dexterite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(21)])),
                ('constition', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(21)])),
                ('intelligence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(21)])),
                ('sagesse', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(21)])),
                ('charisme', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(21)])),
                ('poids', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
